name: Run Compatibility Test

on:
  repository_dispatch:
    types: CompatibilityTest

jobs:
  test:
    name: Test Plugin
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: armory-io/plugin-test-runner@main
        with:
          service: ${{ github.event.client_payload.service }}
          version: ${{ github.event.client_payload.version }}
          plugin_sha: ${{ github.event.client_payload.sha }}
